export const GET_SINGLE_AUCTION_DATA = 'GET_SINGLE_AUCTION_DATA';
export const GET_SINGLE_AUCTION_DATA_SUCCESS =
  'GET_SINGLE_AUCTION_DATA_SUCCESS';
export const GET_SINGLE_AUCTION_DATA_FAILED = 'GET_SINGLE_AUCTION_DATA_FAILED';
