export const UPCOMING_AUCTIONS_REQUEST = 'UPCOMING_AUCTIONS_REQUEST';
export const UPCOMING_AUCTIONS_SUCCESS = 'UPCOMING_AUCTIONS_SUCCESS';
export const CANCELLED_AUCTIONS_REQUEST = 'CANCELLED_AUCTIONS_REQUEST';
export const CANCELLED_AUCTIONS_SUCCESS = 'CANCELLED_AUCTIONS_SUCCESS';
export const COMPLETED_AUCTIONS_REQUEST = 'COMPLETED_AUCTIONS_REQUEST';
export const COMPLETED_AUCTIONS_SUCCESS = 'COMPLETED_AUCTIONS_SUCCESS';
export const WON_AUCTIONS_REQUEST = 'WON_AUCTIONS_REQUEST';
export const WON_AUCTIONS_SUCCESS = 'WON_AUCTIONS_SUCCESS';
