export const USER_NOTIFICATION_REQUEST = 'USER_NOTIFICATION_REQUEST';
export const USER_NOTIFICATION_SUCCESS = 'USER_NOTIFICATION_SUCCESS';
export const USER_NOTIFICATION_FAILED = 'USER_NOTIFICATION_FAILED';
//  Read/Unread Notification
export const USER_NOTIFICATION_REQUEST_READ = 'USER_NOTIFICATION_REQUEST_READ';
export const USER_NOTIFICATION_SUCCESS_READ = 'USER_NOTIFICATION_SUCCESS_READ';
export const USER_NOTIFICATION_FAILED_READ = 'USER_NOTIFICATION_FAILED_READ';
