export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_PHONE_REQUEST = 'USER_PHONE_REQUEST';
export const USER_PHONE_SUCCESS = 'USER_PHONE_SUCCESS';
export const USER_PHONE_FAILED = 'USER_PHONE_FAILED'
