export const NAVIGATION_SCREENS = {
  LOGIN: 'LoginScreen',
  PROFILE: 'Profile',
  SIGNUP: 'SignUpScreen',
  FORGOT_PASSWORD: 'ForgotPassword',
  OTP_SCREEN: 'OtpScreen',
  CREATE_PASSWORD: 'CreatePassword',
  TABNAVIGATOR: 'TabNavigation',
  NOTIFICATION: 'Notifications',
  PACKAGES: 'packages',
  HOMESCREEN: 'HomeScreen',
  AUCTIONSCREEN: 'AuctionScreen',
  DRAWERSCREEN: 'DrawerNavigation',
  AUCTION_DETAIL: 'AuctionDetail',
  SETTING: 'Setting',
  HELPANDSUPPORT: 'Help & Support',
  REFERALANDEARN: 'Referral & Earn',
  TRANSACTIONHOSTORY: 'Transactions History',
  ADD_FUND: 'AddFund',
  PAYMENT_TYPE: 'PatmentMethod',
  WEB_VIEW: 'WebViewScreen',
  WINNERSCREEN:'WinnerScreen',
};
