export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';
//Save Profile/Edit Profile
export const EDIT_USER_PROFILE_REQUEST = 'EDIT_USER_PROFILE_REQUEST';
export const EDIT_USER_PROFILE_SUCCESS = 'EDIT_USER_PROFILE_SUCCESS';
export const EDIT_USER_PROFILE_FAILED = 'EDIT_USER_PROFILE_FAILED';
//EditProfile Pic
export const  EDIT_PROFILE_PIC_REQUEST = 'EDIT_PROFILE_PIC_REQUEST';
export const  EDIT_PROFILE_PIC_SUCCESS = 'EDIT_PROFILE_PIC_SUCCESS';
export const EDIT_PROFILE_PIC_FAILED = 'EDIT_PROFILE_PIC_FAILED';
//Verify Phone 
export const VERIFY_PHONE_REQUEST = 'VERIFY_PHONE_REQUEST';
export const  VERIFY_PHONE_SUCCESS = 'VERIFY_PHONE_SUCCESS';
export const VERIFY_PHONE_FAILED =  'VERIFY_PHONE_FAILED';
export const CHECK_TOKEN_REQUEST = 'CHECK_TOKEN_REQUEST';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAILED = 'CHECK_TOKEN_FAILED';