export const USER_TRANSACTION_REQUEST = 'USER_TRANSACTION_REQUEST';
export const USER_TRANSACTION_SUCCESS = 'USER_TRANSACTION_SUCCESS';
export const USER_TRANSACTION_FAILED = 'USER_TRANSACTION_FAILED';
export const TRANSACTION_CHARGES_REQUEST = 'TRANSACTION_CHARGES_REQUEST';
export const TRANSACTION_CHARGES_SUCCESS = 'TRANSACTION_CHARGES_SUCCESS';
export const USER_PURCHASES_ITEM_REQUEST = 'USER_PURCHASES_ITEM_REQUEST';
export const USER_PURCHASES_ITEM_SUCCESS = 'USER_PURCHASES_ITEM_SUCCESS';
export const REFERRAL_REWARDS_REQUEST = 'REFERRAL_REWARDS_REQUEST';
export const REFERRAL_REWARDS_SUCCESS = 'REFERRAL_REWARDS_SUCCESS';

