export const USER_REGISTER_OTP_REQUEST = 'USER_REGISTER_OTP_REQUEST';
export const USER_REGISTER_OTP_SUCCESS = 'USER_REGISTER_OTP_SUCCESS';
export const USER_REGISTER_OTP_FAILED = 'USER_REGISTER_OTP_FAILED';
export const USER_RESEND_OTP_REQUEST = 'USER_RESEND_OTP_REQUEST';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const CLEAR_PASSWORD_ERROR = 'CLEAR_PASSWORD_ERROR';
