export const ALL_AUCTION_DATA = 'ALL_AUCTION_DATA';
export const ALL_AUCTION_SUCCESS = 'ALL_AUCTION_SUCCESS';
export const JOIN_AUCTION_REQUEST = 'JOIN_AUCTION_REQUEST';
export const JOIN_AUCTION__SUCCESS = 'JOIN_AUCTION__SUCCESS';
export const JOIN_AUCTION__FAILED = 'JOIN_AUCTION__FAILED';
export const LOW_BALENCE = 'LOW_BALENCE';
export const AUCTION_MESSAGE = 'AUCTION_MESSAGE';
